networks:
  eShop:
services:
  # database:
  #   image: mcr.microsoft.com/mssql/server:latest
  #   networks:
  #     - eShop
  #   environment:
  #     ACCEPT_EULA: "Y"
  #     MSSQL_SA_PASSWORD: "Asdqwe123"
  #   ports:
  #     - "1433:1433"
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: Asdqwe123
      POSTGRES_USER: admin
      POSTGRES_DB: eShopDb
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks: 
      - eShop
    restart: unless-stopped
  
  # api:
  #   image: ${DOCKER_REGISTRY-}eshop-api:${PLATFORM:-linux}-${TAG:-latest}
  #   container_name: api_container
  #   build: 
  #     context: ./eShop.Api
  #     dockerfile: eShop.Api/Dockerfile
  #   ports:
  #     - "8000:8080"
  #   depends_on:
  #     - postgres
  #   environment:
  #     - CONNECTION_STRING=Host=localhost;Port=5432;Database=eShopDb;User=admin;Password=Asdqwe123;
  #   networks:
  #     - eShop
volumes:
  postgres:
