version: '3.9'

networks:
  eShop:
services:
  database:
    image: mcr.microsoft.com/mssql/server:latest
    networks:
      - eShop
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Asdqwe123"
    ports:
      - "1433:1433"
