version: '3'

networks:
	eShop:

services:
	database:
		images: mcr.microsoft.com/mssql/server:latest
		restart: always
		networks:
			- eShop
		environment:
			- ACCEPT_EULA=Y
			- SA_PASSWORD=asdqwe123
		ports:
			- 1433:1433